{% set prefix = DEFAULT_CONTAINER_REGISTRY %}
{% if CONFIGURED_ARCH == "armhf" and MULTIARCH_QEMU_ENVIRON == "y" %}
FROM {{ prefix }}multiarch/debian-debootstrap:armhf-stretch
{% elif CONFIGURED_ARCH == "arm64" and MULTIARCH_QEMU_ENVIRON == "y" %}
FROM {{ prefix }}multiarch/debian-debootstrap:arm64-stretch
{% elif PTF_ENV_PY_VER == "mixed" %}
FROM {{ prefix}}debian:buster
{% else %}
FROM {{ prefix }}debian:bullseye
{% endif %}

{% from "dockers/dockerfile-macros.j2" import install_python_wheels, copy_files, install_offending_packages %}

USER root
WORKDIR /root

LABEL maintainer="Pavel Shirshov"

COPY ["sources.list.{{ CONFIGURED_ARCH }}", "/etc/apt/sources.list"]
COPY ["no-check-valid-until", "/etc/apt/apt.conf.d"]
COPY ["apt-retries-count", "/etc/apt/apt.conf.d"]

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Set the apt source, update package cache and install necessary packages
## TODO: Clean up this step
RUN apt-get update          \
    && apt-get upgrade -y   \
    && apt-get dist-upgrade -y  \
    && apt-get install -y   \
        autoconf            \
        openssh-server      \
        vim                 \
        telnet              \
        net-tools           \
        traceroute          \
        lsof                \
        tcpdump             \
        ethtool             \
        unzip               \
        pkg-config          \
        binutils            \
        build-essential     \
        libssl-dev          \
        libffi-dev          \
        wget                \
        cmake               \
        libqt5core5a        \
        libqt5network5      \
{% if PTF_ENV_PY_VER == "mixed" %}
        libboost-atomic1.71.0 \
{% else %}
        libboost-atomic1.74.0 \
        flex                  \
        bison                 \
        tcpd                  \
        libwrap0              \
        libwrap0-dev          \
{% endif %}
        less                \
        git                 \
        iputils-ping        \
        hping3              \
        curl                \
        tmux                \
{% if PTF_ENV_PY_VER == "mixed" %}
        python              \
        python-dev          \
        python-libpcap      \
        python-scapy        \
        python-six          \
{% endif %}
        python3             \
        python3-venv        \
        python3-pip         \
        python3-dev         \
        python3-scapy       \
        python3-six         \
        libpcap-dev         \
{% if PTF_ENV_PY_VER == "mixed" %}
        tacacs+             \
{% endif %}
        rsyslog             \
        ntp                 \
        ntpstat             \
        ntpdate             \
        arping              \
        bridge-utils        \
        libteam-utils       \
        gdb                 \
        automake            \
        iproute2            \
        iptables            \
{% if PTF_ENV_PY_VER != "mixed" %}
        wireshark-common    \
{% endif %}
        freeradius          \
        quilt

# Install Go toolchain for building grpcurl and gnoic from source
# to ensure they use a patched Go stdlib (GO-2026-4337: crypto/tls)
{% if CONFIGURED_ARCH == "armhf" %}
RUN GO_ARCH=armv6l \
    && GO_SHA256=7d4f0d266d871301e08ef4ac31c56e66048688893b2848392e5c600276351ee8 \
{% elif CONFIGURED_ARCH == "arm64" %}
RUN GO_ARCH=arm64 \
    && GO_SHA256=ec342e7389b7f489564ed5463c63b16cf8040023dabc7861256677165a8c0e2b \
{% else %}
RUN GO_ARCH=amd64 \
    && GO_SHA256=00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1 \
{% endif %}
    && GO_VERSION=1.25.9 \
    && curl -L "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" -o /tmp/go.tar.gz \
    && echo "${GO_SHA256}  /tmp/go.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf /tmp/go.tar.gz \
    && rm /tmp/go.tar.gz

ENV PATH="/usr/local/go/bin:$HOME/go/bin:$PATH"

# Build grpcurl from source with patched Go and golang.org/x/* deps
# upgraded to latest to address current and future golang.org/x/* CVEs.
RUN GRPCURL_VERSION=v1.9.3 \
    && git clone --depth 1 --branch "${GRPCURL_VERSION}" https://github.com/fullstorydev/grpcurl.git /tmp/grpcurl \
    && cd /tmp/grpcurl \
    && go get google.golang.org/grpc@v1.79.3 \
    && go get github.com/go-jose/go-jose/v4@latest \
    && go get golang.org/x/crypto@latest golang.org/x/net@latest golang.org/x/text@latest golang.org/x/sys@latest golang.org/x/oauth2@latest \
    && go mod tidy \
    && go build -o /usr/local/bin/grpcurl ./cmd/grpcurl \
    && chmod +x /usr/local/bin/grpcurl \
    && rm -rf /tmp/grpcurl
# Security fixes: upgrade all vulnerable system packages (S360 scan remediation)
RUN apt-get update && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

{% if PTF_ENV_PY_VER == "py3" %}
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 \
    && update-alternatives --install /usr/bin/pdb pdb /usr/bin/pdb3 1 \
    && update-alternatives --install /usr/bin/pydoc pydoc /usr/bin/pydoc3 1 \
    && update-alternatives --install /usr/bin/pygettext pygettext /usr/bin/pygettext3 1
{% endif %}

# Install all python modules from pypi. python-scapy is exception, ptf debian package requires python-scapy
# TODO: Clean up this step
RUN rm -rf /debs \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
{% if PTF_ENV_PY_VER == "mixed" %}
    && wget --https-only https://bootstrap.pypa.io/pip/2.7/get-pip.py \
    && python get-pip.py \
    && rm -f get-pip.py \
    && pip install setuptools \
    && pip install supervisor \
    && pip install ipython \
    && git clone https://github.com/p4lang/scapy-vxlan.git \
    && cd scapy-vxlan \
    && python setup.py install \
    && cd .. \
    && rm -fr scapy-vxlan \
{% else %}
    && wget --https-only https://bootstrap.pypa.io/pip/get-pip.py \
    && python3 get-pip.py \
    && rm -f get-pip.py \
{% endif %}
    && git clone https://github.com/sflow/sflowtool \
    && cd sflowtool \
    && git checkout v6.04 \
    && ./boot.sh \
    && ./configure \
    && make \
    && make install \
    && cd  .. \
    && rm -fr sflowtool \
    && git clone https://github.com/dyninc/OpenBFDD.git \
    && cd OpenBFDD \
    && ./autogen.sh \
    && ./configure \
    && make \
    && make install \
    && cd  .. \
    && rm -fr OpenBFDD \
    && wget https://github.com/nanomsg/nanomsg/archive/1.0.0.tar.gz \
    && tar xvfz 1.0.0.tar.gz \
    && cd nanomsg-1.0.0    \
    && mkdir -p build      \
    && cd build            \
    && cmake ..            \
    && make install        \
    && ldconfig            \
    && cd ../..            \
    && rm -fr nanomsg-1.0.0 \
    && rm -f 1.0.0.tar.gz  \
{% if PTF_ENV_PY_VER == "mixed" %}
    && pip install cffi    \
    && pip install nnpy    \
    && pip install dpkt    \
    && pip install ipaddress \
    && pip install pysubnettree \
    && pip install paramiko \
    && pip install flask   \
    && pip install exabgp==3.4.17\
    && pip install pyaml   \
    && pip install pybrctl pyro4 rpyc yabgp \
    && pip install unittest-xml-reporting \
    && pip install pyrasite \
    && pip install retrying \
{% endif %}
    && mkdir -p /opt       \
    && cd /opt             \
    && wget https://raw.githubusercontent.com/p4lang/ptf/23ebe7237f3c284032bda02fbd1f4a98f1bc12f4/ptf_nn/ptf_nn_agent.py

{% if PTF_ENV_PY_VER == "py3" %}
RUN curl -L -o tacacs.tar.gz https://shrubbery.net/pub/tac_plus/tacacs-F4.0.4.31.tar.gz\
    && mkdir -p tac_plus\
    && tar -xvzf tacacs.tar.gz -C tac_plus\
    && cd tac_plus \
    && cd tacacs-F4.0.4.31 \
    && ./configure LDFLAGS="-Wl,-rpath=/usr/local/lib" \
    && make install \
    && ln -s /usr/local/sbin/tac_plus /usr/sbin/tac_plus \
    && ln -s /usr/local/bin/tac_pwd /usr/sbin/tac_pwd \
    && mkdir /etc/tacacs+ \
    && chmod 0755 /etc/tacacs+
COPY ["tacacs_plus", "/etc/init.d"]
COPY ["tacacs+", "/etc/default"]
{% endif %}

# Workaround: Tornado installed outside of the
# virtualenv as the call to the process API
# Ansible -> Supervisor -> ExaBGP -> Process API
# causes the process API to have a restricted
# environment without access to the virtualenv.
{% if PTF_ENV_PY_VER == "py3" %}
    RUN pip3 install --break-system-packages "tornado>=6.5.5"
{% endif %}


RUN python3 -m venv env-python3
# Activating a virtualenv. The virtualenv automatically works for RUN, ENV and CMD.
ENV VIRTUAL_ENV=/root/env-python3
ARG BACKUP_OF_PATH="$PATH"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONIOENCODING=UTF-8

# Upgrade pip and wheel to address CVE vulnerabilities
RUN pip3 install --upgrade pip "wheel>=0.46.2"

{% if PTF_ENV_PY_VER == "mixed" %}
RUN python3 -m pip install --upgrade --ignore-installed pip
{% endif %}

# For py3 image the following offending packages below do not use the updated 
# setuptools on Python 3.9. The packages downgrade setuptools 
# to 40.x causing further installations to fail
{% if PTF_ENV_PY_VER == "py3" %}
{% set offending_packages = ["supervisor", "ipython", "exabgp==4.2.25", "grpcio-tools", "pybrctl", "pyrasite", "scapy==2.5.0", "thrift"] %}
{{ install_offending_packages(offending_packages) }}
{% else %}
RUN pip3 install setuptools \
        && pip3 install supervisor \
        && pip3 install ipython \
        && pip3 install exabgp==4.2.25 \
        && pip3 install grpcio-tools \
        && pip3 install pybrctl \
        && pip3 install pyrasite \
        && pip3 install scapy==2.5.0 \
        && pip3 install thrift
{% endif %}

# Install all python modules from pypi. python3-scapy is exception, 
# ptf debian package requires python3-scapy
{% if PTF_ENV_PY_VER == "py3" %}
# Werkzeug 3.1.3 has a bug and causes announce routes to fail
# by returning 413 Request Entity Too Large though request buffers
# have been increased.
RUN pip3 install Flask   \
    && pip3 install Werkzeug \
{% else %}
RUN pip3 install Flask \
{% endif %}
    && pip3 install Cython \
    && pip3 install cffi    \
    && pip3 install nnpy    \
    && pip3 install dpkt    \
    && pip3 install ipaddress \
    && pip3 install pysubnettree \
    && pip3 install paramiko \
    && pip3 install "tornado>=6.5.5" \
    && pip3 install Flask   \
    && pip3 install exabgp \
    && pip3 install pyaml   \
    && pip3 install pyro4 rpyc \
    && pip3 install unittest-xml-reporting \
    && pip3 install python-libpcap \
    && pip3 install grpcio \
    && pip3 install protobuf \
    && pip3 install six==1.16.0 \
    && pip3 install itsdangerous \
    && pip3 install retrying \
    && pip3 install jinja2

# Keep protobuf aligned with generated gNMI stubs.
RUN pip3 install protobuf==6.33.5

{% if docker_ptf_whls.strip() -%}
# Copy locally-built Python wheel dependencies
{{ copy_files("python-wheels/", docker_ptf_whls.split(' '), "/python-wheels/") }}

# Install locally-built Python wheel dependencies
{{ install_python_wheels(docker_ptf_whls.split(' ')) }}
{% endif %}

# Deactivating a virtualenv.
ENV PATH="$BACKUP_OF_PATH"

# Ensure setuptools stays in a secure range while retaining pkg_resources
# required by grpc_tools.protoc. setuptools >=78.1.1 restores pkg_resources
# compatibility removed in 78.0 and fixes CVE-2025-47273.
# Upgrade lxml to address GHSA-vfmq-68hx-4jfw
RUN pip3 install "setuptools>=78.1.1" "wheel>=0.46.2" "lxml>=5.3.2"

## Adjust sshd settings
RUN mkdir /var/run/sshd \
    && echo 'root:root' | chpasswd \
    && sed -ri '/^#?PermitRootLogin/c\PermitRootLogin yes' /etc/ssh/sshd_config \
    && sed -ri '/^#?UsePAM/c\UsePAM no' /etc/ssh/sshd_config \
    && sed -ri '/^#?UseDNS/c\UseDNS no' /etc/ssh/sshd_config

COPY supervisord.conf /etc/supervisor/
COPY conf.d/ /etc/supervisor/conf.d/
COPY ptf_tgen.sh /ptf_tgen/

{% if PTF_ENV_PY_VER == "mixed" %}
# Move tcpdump into /usr/bin Otherwise it's impossible to run tcpdump due to a docker bug
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump
RUN ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
{% endif %}

RUN mkdir -p /var/log/supervisor

# Install Python-based GNMI client
RUN git clone https://github.com/google/gnxi.git \
    && cd gnxi \
    && git checkout 208acfa85f5b5b8717e14896e9d6ee93cfda9d5f

COPY gnxi-patches/ gnxi/patches/

RUN cd gnxi \
    && quilt push -a \
    && cd gnmi_cli_py \
{% if PTF_ENV_PY_VER == "mixed" %}
    && pip install -r requirements.txt \
    && pip3 install protobuf==6.33.5 --no-binary=protobuf
{% else %}
    && pip3 install "setuptools>=78.1.1" "grpcio==1.74.0" "grpcio-tools==1.74.0" "protobuf==6.33.5" \
    && rm -f gnmi_pb2.py gnmi_ext_pb2.py gnmi_pb2_grpc.py \
    && wget -q -O gnmi_ext.proto https://raw.githubusercontent.com/openconfig/gnmi/master/proto/gnmi_ext/gnmi_ext.proto \
    && wget -q -O gnmi.proto https://raw.githubusercontent.com/openconfig/gnmi/master/proto/gnmi/gnmi.proto \
    && sed -i 's|github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.proto|gnmi_ext.proto|' gnmi.proto \
    && python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. gnmi_ext.proto gnmi.proto \
    && if grep -q _internal_create_key gnmi_ext_pb2.py; then echo "ERROR: gnmi stubs generated with incompatible protoc"; exit 1; fi \
    && rm -f gnmi.proto gnmi_ext.proto \
    && cat requirements.txt | grep -Ev '^(futures|grpcio==|grpcio-tools==|protobuf==)' > /tmp/requirements.txt \
    && pip3 install -r /tmp/requirements.txt \
    && pip3 install "setuptools>=78.1.1" "grpcio==1.74.0" "grpcio-tools==1.74.0" "protobuf==6.33.5"
{% endif %}

# Deactivating a virtualenv.
# ENV PATH="$BACKUP_OF_PATH"


COPY \
{% for deb in docker_ptf_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_ptf_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

# Remove Go toolchain to reduce image size
RUN rm -rf /usr/local/go "$(go env GOPATH 2>/dev/null || echo $HOME/go)"
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Apply pending Debian security updates.
# The build system pins package versions via /etc/apt/preferences.d/01-versions-deb.
# Remove the pin so apt-get upgrade can pull in the latest security patches.
RUN rm -f /etc/apt/preferences.d/01-versions-deb \
    && apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

# Final system-level security upgrade: ensure every Debian package is at its
# latest patched version from the security repos.  This must run AFTER all
# apt-get install / dpkg -i steps so nothing slips through.
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y \
    && rm -rf /var/lib/apt/lists/*

# There are some scripts like supervisorctl and others invoked from
# custom Ansible modules which use exec_command to run these. Since
# Ansible module's exec_command uses a restricted shell without sourcing
# the profile or other rc files the PATH does not include the virtualenv.
# This step keeps links to required binaries from /usr/local/bin to the
# virtualenv bin directory.
RUN set -eux; \
  for f in /root/env-python3/bin/*; do \
    base="$(basename "$f")"; \
    case "$base" in \
      python*|pip*) continue ;; \
    esac; \
    ln -sf "$f" "/usr/local/bin/$base"; \
  done

RUN echo "/root/env-python3/lib/python3.9/site-packages" > /usr/lib/python3/dist-packages/virtualenv.pth

RUN echo "PYTHONPATH=/root/env-python3/lib/python3.9/site-packages" >> /etc/environment

# Final system-level security upgrade: ensure every Debian package is at its
# latest patched version. This must run AFTER all apt-get install / dpkg -i
# steps so nothing slips through.
# Covers OpenSSL, openssh, libpng, gdk-pixbuf, inetutils, tiff CVEs.
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y \
    && rm -rf /var/lib/apt/lists/*

COPY ["*.ini", "/etc/ptf/"]
EXPOSE 22 8009

ENTRYPOINT ["/root/env-python3/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]