#!/usr/bin/env python3
import time
import sys
import signal
import subprocess
import traceback
from sonic_py_common import logger
from utilities_common.util_base import UtilHelper

def graceful_exit(signum, frame):
    time.sleep(1)
    sys.exit(0)

signal.signal(signal.SIGTERM, graceful_exit)
signal.signal(signal.SIGINT, graceful_exit)

def run():
    helper = UtilHelper()
    platform_chassis = helper.load_platform_chassis()
    SYSLOG_IDENTIFIER = "ufispaceAsicThermalMonitor"
    helper_logger = logger.Logger(SYSLOG_IDENTIFIER)


    if not helper.check_pddf_mode():
        helper_logger.log_error("PDDF mode should be supported and enabled for this platform for this operation", True)
        sys.exit(1)

    if not platform_chassis:
        helper_logger.log_error("Platform_chassis is empity", True)
        sys.exit(1)

    # We delay N second to start
    time.sleep(60)
    while True:
        thermal_list = platform_chassis.get_all_thermals()
        default_index = 0

        for _, thermal in enumerate(thermal_list, default_index):
            if not thermal.__class__.__name__ == 'AsicThermal':
                continue

            try:
                temp = thermal.get_temperature()
                cmd = [
                        "ipmitool", "raw", "0x3c", "0x20", "0x0",
                        str(thermal.sensor_db_index), str(int(temp)),
                        "0x1"
                ]

                if temp != 0:
                    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=3)
            except Exception as e:
                # helper_logger.log_error(traceback.format_exc(), True)
                pass

        time.sleep(2)

if __name__ == "__main__":
    run()