# Broadcom SAI modules

BRCM_OPENNSL_KERNEL = saiufi-modules_1.0.0_amd64_6.1.0-22-2.deb
$(BRCM_OPENNSL_KERNEL)_PATH = files/ufi/lib/
#$(BRCM_OPENNSL_KERNEL)_URL = ""
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_OPENNSL_KERNEL)_MACHINE = broadcom
SONIC_COPY_DEBS += $(BRCM_OPENNSL_KERNEL)
#SONIC_ONLINE_DEBS += $(BRCM_OPENNSL_KERNEL)


## SAI bcm modules for DNX family ASIC

BRCM_DNX_OPENNSL_KERNEL = saiufi-modules-dnx_1.0.0_amd64_6.1.0-22-2.deb
$(BRCM_DNX_OPENNSL_KERNEL)_PATH = files/ufi/lib/
#$(BRCM_DNX_OPENNSL_KERNEL)_URL = ""
$(BRCM_DNX_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_DNX_OPENNSL_KERNEL)_MACHINE = broadcom-dnx
$(BRCM_DNX_OPENNSL_KERNEL)_AFTER = $(BRCM_OPENNSL_KERNEL)
SONIC_COPY_DEBS += $(BRCM_DNX_OPENNSL_KERNEL)
#SONIC_ONLINE_DEBS += $(BRCM_DNX_OPENNSL_KERNEL)
